export interface Industry {
  id: number;
  name: string;
}

export const industries = [
  { id: 1, name: "Web Development" },
  { id: 2, name: "Graphic Design" },
  { id: 3, name: "Game Development" },
  { id: 4, name: "Music" },
  { id: 5, name: "Film" },
];

export interface Status {
  id: number;
  name: string;
}

export const status = [
  { id: 1, name: "Not started" },
  { id: 2, name: "In progress" },
  { id: 3, name: "Completed" },
];

export interface Skill {
  id: number;
  name: string;
}

export const skills = [
  // Web Development
  { id: 1, name: "HTML" },
  { id: 2, name: "CSS" },
  { id: 3, name: "JavaScript" },
  { id: 4, name: "TypeScript" },
  { id: 5, name: "React" },
  { id: 6, name: "Angular" },
  { id: 7, name: "Vue.js" },
  { id: 8, name: "Node.js" },
  { id: 9, name: "Python" },
  { id: 10, name: "Django" },
  { id: 11, name: "Ruby on Rails" },
  { id: 12, name: "PHP" },
  { id: 13, name: "Laravel" },
  { id: 14, name: "WordPress" },
  { id: 15, name: "Magento" },
  { id: 16, name: "Shopify" },
  { id: 17, name: "WooCommerce" },
  { id: 18, name: "Java" },
  { id: 19, name: "Spring Boot" },
  { id: 20, name: "ASP.NET" },
  { id: 21, name: "SQL" },
  { id: 22, name: "NoSQL" },
  { id: 23, name: "GraphQL" },
  { id: 24, name: "Docker" },
  { id: 25, name: "Git" },

  // Graphic Design
  { id: 26, name: "Adobe Photoshop" },
  { id: 27, name: "Adobe Illustrator" },
  { id: 28, name: "Adobe InDesign" },
  { id: 29, name: "Sketch" },
  { id: 30, name: "Figma" },
  { id: 31, name: "CorelDraw" },
  { id: 32, name: "Affinity Designer" },
  { id: 33, name: "GIMP" },
  { id: 34, name: "Blender" },
  { id: 35, name: "3D Studio Max" },
  { id: 36, name: "Maya" },
  { id: 37, name: "Cinema 4D" },
  { id: 38, name: "QuarkXPress" },
  { id: 39, name: "Inkscape" },
  { id: 40, name: "UX/UI Design" },
  { id: 41, name: "HTML" },
  { id: 42, name: "CSS" },
  { id: 43, name: "JavaScript" },
  { id: 44, name: "WebGL" },
  { id: 45, name: "AR/VR Design" },
  { id: 46, name: "Motion Graphics" },
  { id: 47, name: "Typography" },
  { id: 48, name: "Color Theory" },
  { id: 49, name: "Print Design" },
  { id: 50, name: "Digital Illustration" },

  // Game Development
  { id: 51, name: "Unity" },
  { id: 52, name: "Unreal Engine" },
  { id: 53, name: "Godot" },
  { id: 54, name: "C#" },
  { id: 55, name: "C++" },
  { id: 56, name: "Python" },
  { id: 57, name: "Java" },
  { id: 58, name: "Swift" },
  { id: 59, name: "HTML5" },
  { id: 60, name: "CSS3" },
  { id: 61, name: "JavaScript" },
  { id: 62, name: "WebGL" },
  { id: 63, name: "DirectX" },
  { id: 64, name: "OpenGL" },
  { id: 65, name: "Vulkan" },
  { id: 66, name: "Shader Programming" },
  { id: 67, name: "Physics Engines" },
  { id: 68, name: "Artificial Intelligence in Gaming" },
  { id: 69, name: "Game Design" },
  { id: 70, name: "3D Modeling" },
  { id: 71, name: "2D Artwork" },
  { id: 72, name: "Texture Art" },
  { id: 73, name: "Sound Design" },
  { id: 74, name: "Narrative Design" },
  { id: 75, name: "QA and Testing" },

  // Music
  { id: 76, name: "Ableton Live" },
  { id: 77, name: "FL Studio" },
  { id: 78, name: "Pro Tools" },
  { id: 79, name: "Logic Pro X" },
  { id: 80, name: "GarageBand" },
  { id: 81, name: "Cubase" },
  { id: 82, name: "Reason" },
  { id: 83, name: "Reaper" },
  { id: 84, name: "Sibelius" },
  { id: 85, name: "Finale" },
  { id: 86, name: "Audacity" },
  { id: 87, name: "Adobe Audition" },
  { id: 88, name: "Sound Forge" },
  { id: 89, name: "Virtual DJ" },
  { id: 90, name: "Serato DJ" },
  { id: 91, name: "Traktor Pro" },
  { id: 92, name: "Max/MSP" },
  { id: 93, name: "Pure Data" },
  { id: 94, name: "Cakewalk" },
  { id: 95, name: "WavePad" },
  { id: 96, name: "Studio One" },
  { id: 97, name: "BandLab" },
  { id: 98, name: "LMMS" },
  { id: 99, name: "Bitwig Studio" },
  { id: 100, name: "Nuendo" },

  // Film
  { id: 101, name: "Adobe Premiere Pro" },
  { id: 102, name: "Final Cut Pro" },
  { id: 103, name: "DaVinci Resolve" },
  { id: 104, name: "Avid Media Composer" },
  { id: 105, name: "Sony Vegas Pro" },
  { id: 106, name: "Lightworks" },
  { id: 107, name: "Cinema 4D" },
  { id: 108, name: "After Effects" },
  { id: 109, name: "Blender" },
  { id: 110, name: "Maya" },
  { id: 111, name: "3ds Max" },
  { id: 112, name: "Nuke" },
  { id: 113, name: "Autodesk Smoke" },
  { id: 114, name: "Motion" },
  { id: 115, name: "HitFilm Pro" },
  { id: 116, name: "Adobe SpeedGrade" },
  { id: 117, name: "Colorista" },
  { id: 118, name: "Filmora" },
  { id: 119, name: "Pinnacle Studio" },
  { id: 120, name: "Corel VideoStudio" },
  { id: 121, name: "Adobe Story" },
  { id: 122, name: "Celtx" },
  { id: 123, name: "Final Draft" },
  { id: 124, name: "Shotcut" },
  { id: 125, name: "Avidemux" },
];
