import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import keycloak from "./keycloak/keycloak";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lagalt - The Collaboration Platform",
  description: "Generated by create next app",
};

// Initialize Keycloak and check authentication status
const initializeKeycloak = () => {
  if (keycloak) {
    console.log("Keycloak object:", keycloak);
    try {
      keycloak.init({ onLoad: 'check-sso' });
    } catch (error) {
      console.error("Error initializing Keycloak:", error);
    }
  } else {
    console.error("Keycloak object is not defined.");
  }
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  initializeKeycloak();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
