import { UserProvider } from "@/app/contexts/userContext";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import AuthStatus from "./components/authStatus";
import SessionProviderWrapper from "@/utils/sessionProviderWrapper"

// export const metadata: Metadata = {
//   title: "Lagalt - The Collaboration Platform",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionProviderWrapper>
      <UserProvider>
        <html lang="en">
          <body>
            <AuthStatus />
            <Navbar />
            {children}
          </body>
        </html>
      </UserProvider>
    </SessionProviderWrapper>
  );
}
